name: gradution_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # مكتبات تمت إضافتها
  image_picker: ^1.0.4 
  flutter_tts: ^4.2.3 
  speech_to_text: ^7.3.0 
  vibration: ^3.1.4 
  
  # مكتبات Firebase والشبكة
  firebase_core: ^4.2.1 
  http: ^1.1.0 
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # تم تحديث الإصدار لتجنب التحذيرات القديمة
  flutter_lints: ^6.0.0 

flutter:
  uses-material-design: true

  # يجب أن تكون assets تحت flutter بمسافتين
  assets:
    - lib/assets/
    # إذا كنتِ تستخدمين هذه الصورة، قومي بإزالة علامة #
    # - lib/assets/eldry.png
    